### ISSUE TITLE
FirstOrFail() doesn't work 

### ISSUE THREAD

**Issue by AEK-BKF** [lorisleiva/laravel-search-string#14]
Hi,

I have this query works fine :
`$post = BlogPost::usingSearchString('published slug:'.$slug.' limit:1')->get()->first();`
But I need to use **firstOrFail()** method to handle empty result.
Could you please fix it.

Thanks

**Comment by lorisleiva** [comment]
Hi there 👋 

I'm afraid I cannot reproduce this bug. The following test passes.

<img width="672" alt="Screenshot 2020-04-05 at 16 05 12" src="https://user-images.githubusercontent.com/3642397/78502112-4ca58f00-7757-11ea-9354-2860ca40f9b3.png">

If you can reproduce this bug with a fresh Laravel install and give me the steps, I will gladly reopen this issue.

Thank you for your understanding.
