### ISSUE TITLE
Using "no-results" when paginating yields no fruit

### ISSUE THREAD

**Issue by mikerockett** [lorisleiva/laravel-search-string#16]
Internally, the LengthAwarePaginator will use skip and take/limit to determine the correct set of results to return, as intended.

However, when using `no-results` in `search-string.fail`, all results are returned anyway when the query-build fails.

Naturally, this is not a bug, but rather an oversight, one that I can't figure out how to solve without manually paginating results, which isn't necessarily desirable.

I have a feeling that a solution isn't really possible here. As such, the readme should be probably updated to include a note about this. Perhaps something along the lines of:

> **Note:** Attempting to silently fail with `no-results` will fall-back to `all-results` when paginating a query-builder result. This is because, internally, the LengthAwarePaginator will override the intended behaviour by setting `skip` and `take`.

I'd submit a PR, but would prefer to run this by you first – for all we know, a solution might be out there, somewhere. 🙃

**Comment by lorisleiva** [comment]
Hi there 👋 

Very well spotted thank you!

I agree, adding this to the documentation is the right thing to do.

A PR for this is most welcome. 🙇 🙂

**Comment by mikerockett** [comment]
Thanks! PR opened with a note at the bottom of the readme. 🙂
