### ISSUE TITLE
Default columns not being used

### ISSUE THREAD

**Issue by mikerockett** [lorisleiva/laravel-search-string#17]
The readme states that search queries (that is, the portion of the query that does not define a column to look at) will look at all searchable columns. However, this doesn't appear to be the case for me.

In my `Issue` model, I have the following:

```php
public function getSearchStringOptions(): array
{
  return [
    'columns' => [
      'title',
      'severity' => [
        'map' => Severity::values(),
      ],
    ],
  ];
}
```

Searching `title:Example` works and returns all issues where the title is like `%Example%`. However, searching for `Example` returns everything. Searching `Example severity:medium` returns all issues with a severity of `medium`, as mapped.

Upon investigating the generated query, it looks like nothing is built up to accomodate for the lone `Example` (quoted or not).

Is there something I'm missing, or is this a bug?

**Comment by lorisleiva** [comment]
Hi there 👋 

From the configuration shown above, you have no columns defined as searchable.

The query string `title:Example` will not (or at least should not) match `%Example%` but rather the exact `"Example"` string.

For you to be able to use solo strings such as `Example`, you need to define at least one column as searchable. In your case, this would be:

```php
public function getSearchStringOptions(): array
{
  return [
    'columns' => [
      'title' => [
        'searchable' => true,
      ],
      'severity' => [
        'map' => Severity::values(),
      ],
    ],
  ];
}
```

I hope this helps. 🍀

**Comment by mikerockett** [comment]
Riiight, that makes sense. Definitely missed something then!

Thanks, and awesome work on this :)
