### ISSUE TITLE
requires illuminate/support >=5.5 <=5.8

### ISSUE THREAD

**Issue by sergeByishimo** [lorisleiva/laravel-search-string#2]
Please increase the maximum version number to support versions greater than 5.8.0 ( like 5.8.13 ) like other packages. Thanks!

Composer error upon installation :

Problem 1
    - Installation request for lorisleiva/laravel-search-string ^0.1.1 -> satisfiable by lorisleiva/laravel-search-string[v0.1.1].
    - Conclusion: remove laravel/framework v5.8.13
    - Conclusion: don't install laravel/framework v5.8.13
    - lorisleiva/laravel-search-string v0.1.1 requires illuminate/support >=5.5 <=5.8 -> satisfiable by laravel/framework[v5.8.0], illuminate/support[ v5.7.0, v5.7.1, v5.7.10, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0].
    - Can only install one of: laravel/framework[v5.8.0, v5.8.13].
    - don't install illuminate/support v5.7.9|don't install laravel/framework v5.8.13
    - don't install illuminate/support v5.8.0|don't install laravel/framework v5.8.13
    - Installation request for laravel/framework (locked at v5.8.13, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.13].

**Comment by lorisleiva** [comment]
Hi there 👋 

Thanks for reporting this issue.

I've updated the `composer.json` and deployed a new release (`v0.1.2`).

Could you please let me know if that fixes this issue? 🤞

**Comment by sergeByishimo** [comment]
It worked like magic!!
