### ISSUE TITLE
HoaCompiler error after update

### ISSUE THREAD

**Issue by denisdulici** [lorisleiva/laravel-search-string#20]
First of all, congrats @lorisleiva on the new version, the new grammar and relationships look awesome 😉 

I tried to update [Akaunting](https://github.com/akaunting/akaunting) but got the attached error. It's the index page without any search applied yet. Any clue?

Using the latest Laravel on PHP 7.2 version.

![Screenshot_25](https://user-images.githubusercontent.com/5254835/86494632-97e33400-bd7e-11ea-9155-1b0ae56ed805.jpg)

**Comment by lorisleiva** [comment]
Hi Denis 👋 

Thank you so much for looking into this so quickly. It should just be the case of allowing the manager to handle empty strings. I’ll make sure to get that sorted this weekend! 🙂

**Comment by lorisleiva** [comment]
I've managed to clone the Akaunting repo (amazing job btw!) and reproduce the error when updating `laravel-search-string`.

This is now fixed and released in version [`v1.0.1`](https://github.com/lorisleiva/laravel-search-string/releases/tag/v1.0.1).

Thank you for reporting this! Let me know if you have any other issues with the upgrade. 🙂

**Comment by denisdulici** [comment]
Thank you Loris, just tried and worked like a charm 😉
