### ISSUE TITLE
belongsToMany - how to configure?

### ISSUE THREAD

**Issue by relayer464** [lorisleiva/laravel-search-string#29]
I currently have a project where I use a **belongsToMany** relationship on `posts` table that links to a `tags` table.  I saw where the documentation says the belongsToMany relationship is supported.  The documentation example shows how to use the **hasMany** relationship.   I have added the SearchString trait to both models (Post and Tag) and included the following columns configuration:  

`'tags' => ['relationship' => true], `

Unfortunately I can't seem to get it to work.  Should the **belongsToMany** relationship be configured in a different way?

Ideally I would like users to be able to perform keyword search of the `posts` table and match it against standard column values or my tag names being displayed as part of a belongsToMany relationship.  Is this possible?

Thank you for making a very nice package.  All the search options are awesome!

**Comment by lorisleiva** [comment]
Hi there 👋 

You make a good point. I have had to search through a many-to-many yet using this package so something could be wrong.

In theory though, the package builds the relationship constraint using `$builder->has(...)`. That means it should work with any type of relationship that is not polymorphic.

Using the setup you've mentioned above, what SQL query do you end up getting when you search something like: `tags > 3`?

Could you try a few different queries using the following code and share them here?

```php
Post::usingSearchString('tags > 10')->toSql();
```

Thank you for raising this! 🙇‍♂️

**Comment by relayer464** [comment]
Thank you for the suggestion.   When I tried using `Post::usingSearchString('tags > 10')->toSql();` it returns all records, including  those that do not have any tags.  

I decided to remove all previous configurations, clear cache, and redo my configuration.   I actually got tag searching based on the belongsToMany relationship working (hurray!) using the following: 

`Post::usingSearchString('tags:(Education)')`

However, if if I try to search the standard Post fields, like,

`Post::usingSearchString('library')`

then I get the following SQL error:

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tags' in 'where clause' `

Here is my columns configuration:
```
    protected $searchStringColumns = [
        "name" => ["searchable" => true],
        "description" => ["searchable" => true],            
        'tags' => [
            "searchable" => true,
            'relationship' => true,
            ], 
    ];
```
Obviously tags is not a field but the relationship name.  If I remove the tags relationship I can search the name and description fields on the Post just fine.   In short, my problem now is I can't make them work together.  Perhaps my configuration is incorrect?   

I read through the documentation several times.  I thought perhaps a somewhat more sophisticated query, like putting both searches together like,

`Post::usingSearchString('(Education) OR (tags:(Education))')`

...might do the trick.  However, I still get the SQL error:

`Column not found: 1054 Unknown column 'tags' in 'where clause' `

Any ideas or suggestions would be much appreciated.  Thanks!

**Comment by relayer464** [comment]
Okay, I think I got it figured out.  I changed the searchable option on tags to false as follows and it appears to be working.  In other words, no SQL error anymore.  I should have tried this earlier...my bad.

```
        'tags' => [
            "searchable" => false,
```
I think everything is good.  Thanks again for a terrific package!

**Comment by lorisleiva** [comment]
Oh I see! Yes sorry I didn't spot that but `searchable` means it's going to add a WHERE LIKE clause on your query builder which is not going to work on a relationship column.

Thanks for providing your findings, I'm sure that will help others having the same issue. 🙂
