### ISSUE TITLE
sort not using value of key property 

### ISSUE THREAD

**Issue by ahmedbally** [lorisleiva/laravel-search-string#34]
`sort:-created`
not working lead to  exception

**Comment by lorisleiva** [comment]
Hi there, what's the exception?

**Comment by ahmedbally** [comment]
Query Exception 
As in query builder result 
`OrderBy created`
Not 
`OrderBy created_at`
Failed on mapping values

**Comment by lorisleiva** [comment]
Thanks, can I see your column definition for that `created_at` field?

**Comment by ahmedbally** [comment]
` 'created_at'=>[
            'key'=>'created'
        ],`
and its casted as datetime in casts

**Comment by lorisleiva** [comment]
Thank you, I’ll sort this out when I have a moment. Hopefully this week. ☺️

**Comment by lorisleiva** [comment]
All fixed and released as `v1.1.3`. Let me know if that all works for you. 🙂
