### ISSUE TITLE
search in transitable attributes 

### ISSUE THREAD

**Issue by ahmedbally** [lorisleiva/laravel-search-string#37]
I want to  search in transitable attributes
I used this package 
https://github.com/Astrotomic/laravel-translatable
how could I use  their function "whereTranslationLike" instead of "where"
if you could make callback function for attribute to  override its behavior if possible
thanks

**Comment by lorisleiva** [comment]
Hi there 👋 

This isn't supported at the moment.

You'd need to override the [`BuildColumnsVisitor`](https://github.com/lorisleiva/laravel-search-string/blob/main/src/Visitors/BuildColumnsVisitor.php) and make sure to use it via the [`getSearchStringVisitors`](https://github.com/lorisleiva/laravel-search-string/blob/366f5584f2ae13d6751644f05079f2c0d6634c0e/src/Concerns/SearchString.php#L31) method.
