### ISSUE TITLE
Error using PHPstan

### ISSUE THREAD

**Issue by masterix21** [lorisleiva/laravel-search-string#40]
Using your package seem impossible to use PHPstan, due to the error:
```
Fatal error: Cannot declare class Hoa\Protocol\Wrapper, because the name is already in use in /Users/luca/Projects/***/vendor/sanmai/hoa-protocol/Source/Wrapper.php on line 44
```

Check the attachment.

![image](https://user-images.githubusercontent.com/6555012/132946130-d659f7f7-b67a-4543-a9e5-df71d7d4bdf8.png)

I'm using Laravel 8.60.0 with PHP 8.0.3.

**Comment by masterix21** [comment]
The bug depends due the package `sanmai/hoa-protocol`. I'm closing here.

**Comment by lorisleiva** [comment]
Hi there 👋 

You're right but there is some much weirdness with the HOA compiler that I've been thinking of replacing it with another for a while now.

It does the job perfectly but because technology evolves around it and it's not updated, it becomes less and less a viable option.

**Comment by masterix21** [comment]
Moreover, seems to be abandoned.

![image](https://user-images.githubusercontent.com/6555012/134890756-81471a92-1db2-4f9b-b114-487bb905e133.png)
